// Pre-seeded read-only demo simulator shown to guest users.
// Uses id: -1 as a sentinel — never persisted to localStorage or migrated.

import type { Simulation } from "@/app/simulator/SimulatorClient";

export const DEMO_SIMULATION_ID = -1;

export const DEMO_SIMULATION: Simulation = {
    id: DEMO_SIMULATION_ID,
    name: "Demo: SMA Crossover",
    cash_balance: 11847.3,
    starting_cash: 10000,
    status: "Pause Trading",
    frequency: "daily",
    price_mode: "close",
    strategy_name: "sma_crossover",
    last_run_at: "2025-04-10T20:00:00Z",
    next_run_at: null,
    max_position_pct: 20,
    max_daily_loss_pct: 5,
    stopped_reason: null,
    stocks: [
        {
            symbol: "AAPL",
            companyName: "Apple Inc.",
            trackedId: null,
            price: 172.43,
            change: 1.23,
            changePercent: 0.72,
        },
        {
            symbol: "MSFT",
            companyName: "Microsoft Corporation",
            trackedId: null,
            price: 415.28,
            change: -2.14,
            changePercent: -0.51,
        },
        {
            symbol: "NVDA",
            companyName: "NVIDIA Corporation",
            trackedId: null,
            price: 881.6,
            change: 14.3,
            changePercent: 1.65,
        },
    ],
    trades: [
        {
            id: "demo-1",
            symbol: "AAPL",
            action: "BUY",
            price: 168.4,
            shares: 12,
            timestamp: new Date("2025-04-10T09:32:00Z"),
            cashAfter: 8979.2,
        },
        {
            id: "demo-2",
            symbol: "MSFT",
            action: "BUY",
            price: 412.1,
            shares: 4,
            timestamp: new Date("2025-04-10T09:34:00Z"),
            cashAfter: 7330.8,
        },
        {
            id: "demo-3",
            symbol: "AAPL",
            action: "HOLD",
            price: 169.2,
            shares: 0,
            timestamp: new Date("2025-04-10T10:00:00Z"),
            cashAfter: 7330.8,
        },
        {
            id: "demo-4",
            symbol: "NVDA",
            action: "BUY",
            price: 868.5,
            shares: 2,
            timestamp: new Date("2025-04-10T10:30:00Z"),
            cashAfter: 5593.8,
        },
        {
            id: "demo-5",
            symbol: "MSFT",
            action: "HOLD",
            price: 413.8,
            shares: 0,
            timestamp: new Date("2025-04-10T11:15:00Z"),
            cashAfter: 5593.8,
        },
        {
            id: "demo-6",
            symbol: "AAPL",
            action: "BUY",
            price: 170.1,
            shares: 5,
            timestamp: new Date("2025-04-10T11:45:00Z"),
            cashAfter: 4743.3,
        },
        {
            id: "demo-7",
            symbol: "NVDA",
            action: "SELL",
            price: 874.2,
            shares: 1,
            timestamp: new Date("2025-04-10T13:00:00Z"),
            cashAfter: 5617.5,
        },
        {
            id: "demo-8",
            symbol: "MSFT",
            action: "SELL",
            price: 417.6,
            shares: 2,
            timestamp: new Date("2025-04-10T13:30:00Z"),
            cashAfter: 6452.7,
        },
        {
            id: "demo-9",
            symbol: "AAPL",
            action: "HOLD",
            price: 171.5,
            shares: 0,
            timestamp: new Date("2025-04-10T14:00:00Z"),
            cashAfter: 6452.7,
        },
        {
            id: "demo-10",
            symbol: "NVDA",
            action: "SELL",
            price: 879.9,
            shares: 1,
            timestamp: new Date("2025-04-10T14:30:00Z"),
            cashAfter: 7332.6,
        },
        {
            id: "demo-11",
            symbol: "AAPL",
            action: "SELL",
            price: 172.0,
            shares: 8,
            timestamp: new Date("2025-04-10T15:00:00Z"),
            cashAfter: 8708.6,
        },
        {
            id: "demo-12",
            symbol: "MSFT",
            action: "SELL",
            price: 415.8,
            shares: 2,
            timestamp: new Date("2025-04-10T15:30:00Z"),
            cashAfter: 9540.2,
        },
        {
            id: "demo-13",
            symbol: "AAPL",
            action: "SELL",
            price: 172.43,
            shares: 9,
            timestamp: new Date("2025-04-10T15:55:00Z"),
            cashAfter: 11091.07,
        },
        {
            id: "demo-14",
            symbol: "NVDA",
            action: "HOLD",
            price: 881.6,
            shares: 0,
            timestamp: new Date("2025-04-10T15:58:00Z"),
            cashAfter: 11091.07,
        },
        {
            id: "demo-15",
            symbol: "MSFT",
            action: "HOLD",
            price: 415.28,
            shares: 0,
            timestamp: new Date("2025-04-10T15:59:00Z"),
            cashAfter: 11847.3,
        },
    ],
};
